### 使用numpy 读写数据

In [1]:
import numpy as np

In [3]:
%%writefile z.txt
1 2 3 4 5 6
2 3 4 5 7 7

Overwriting z.txt


In [9]:
data =[]
with open('z.txt') as f:
    for line in f.readlines():
        fields = line.split()
        cur_data = [float(x) for x in fields]
        data.append(cur_data)
print(data)
data = np.array(data)
data

[[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], [2.0, 3.0, 4.0, 5.0, 7.0, 7.0]]


array([[1., 2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 7., 7.]])

In [15]:
# 简单做到以上，默认以空格为分隔符，可以指定，还可以指定跳过几行
data = np.loadtxt('z.txt', delimiter=' ', skiprows=1)
print(data)

[2. 3. 4. 5. 7. 7.]


* 'z.txt'：路径最好放到和代码一起
* skiprows：去掉几行
* delimiter：分隔符
* usecols=(0,1,4)指定使用哪几列

### 使用Numpy 写数据

In [20]:
z_array = np.array([[1,2,3], [4,5,6]])

In [22]:
# fmt，指定保存格式%d整数,%f浮点数，delimiter指定保存分隔符
np.savetxt('z1.txt', z_array,fmt='%d', delimiter=',')

### 读写array结构

In [26]:
z_array = np.array([[1,2,3], [4,5,6]])
# 直接打开 会有格式错误
np.save('z_array.npy', z_array)

In [27]:
# np.load可以加载 .npy
z_array = np.load('z_array.npy')
print(z_array)

[[1 2 3]
 [4 5 6]]


In [29]:
z_array2 = np.arange(10)
z_array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
# 相当于压缩，存储多个 ndarray，将多个npy压缩成一个npz
np.savez('z.npz',z_array=z_array,b=z_array2)

In [33]:
data = np.load('z.npz')

In [41]:
print(list(data.keys()))

['z_array', 'b']


In [40]:
data.get("b")

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
data["z_array"]

array([[1, 2, 3],
       [4, 5, 6]])