### 数组形状操作

In [20]:
import numpy as np
# arange 构造数组
z_array = np.arange(10)
z_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
z_array.shape

(10,)

In [22]:
# 改变原数组shape，总元素数不能变
z_array.shape = 2,5
z_array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [23]:
# 使用reshape，生成新的ndarray
z_array.reshape(5,2)
z_array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [27]:
# 新增维度
z_array = np.arange(10)
z_array = z_array[np.newaxis,:]
z_array

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [28]:
z_array.shape

(1, 10)

In [29]:
# 去掉空的轴，压缩;值为1的轴
z_array = z_array.squeeze()
z_array.shape

(10,)

In [42]:
#z_array.shape=2,5
# 转置
z_array = z_array.transpose()
print(z_array)

[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [43]:
z_array.T

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### ndarray的链接

In [45]:
a = np.array([[12,35,657],[234,564,767],[123,345,567]])
b = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [50]:
# 默认以 axis=0 维度进行连接
c = np.concatenate((a,b))
c

array([[ 12,  35, 657,   1,   2,   3],
       [234, 564, 767,   4,   5,   6],
       [123, 345, 567,   7,   8,   9]])

In [51]:
c = np.concatenate((a,b),axis=1)
c

array([[ 12,  35, 657,   1,   2,   3],
       [234, 564, 767,   4,   5,   6],
       [123, 345, 567,   7,   8,   9]])

In [52]:
# vstack 相当于 concatenate 轴为0
d = np.vstack((a,b))

array([[ 12,  35, 657],
       [234, 564, 767],
       [123, 345, 567],
       [  1,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [54]:
# hstack 相当于 concatenate 轴为1
d = np.hstack((a,b))
d

array([[ 12,  35, 657,   1,   2,   3],
       [234, 564, 767,   4,   5,   6],
       [123, 345, 567,   7,   8,   9]])

In [56]:
# 拉平操作
a.flatten()

array([ 12,  35, 657, 234, 564, 767, 123, 345, 567])

In [57]:
a.ravel()

array([ 12,  35, 657, 234, 564, 767, 123, 345, 567])

In [58]:
a

array([[ 12,  35, 657],
       [234, 564, 767],
       [123, 345, 567]])