In [1]:
import numpy as np

### 对于ndarray结构来说，里面所有元素必须是同一类型，为了底层计算的高效性；
### 如果不是的话，会自动向下进行转换

In [22]:
z_list = [1,2,3,4,5]

In [23]:
z_array = np.array(z_list)
z_array

array([1, 2, 3, 4, 5])

In [24]:
type(z_array)

numpy.ndarray

### 基本属性操作

In [25]:
z_array.dtype # array 中值得类型

dtype('int64')

In [26]:
z_array.itemsize # 查看ndarray中元素占用空间

8

In [30]:
z_array.shape # 查看ndarray结构，一维5个元素
np.shape(z_array)

(5,)

In [31]:
z_array.size # ndarray中有多少元素，不关心维度，只知道总数
np.size(z_list)

5

In [33]:
z_array.ndim # 查看 ndarray 的维度

1

In [36]:
z_array.fill(0) # 向矩阵中填充值
z_array

array([0, 0, 0, 0, 0])

# 索引与切片，跟python都一样，都是从零开始的

In [38]:
z_list = [1,2,3,4,5]
z_array = np.array(z_list)
z_array[0]

1

In [39]:
z_array[1:3]

array([2, 3])

In [40]:
z_array[-2:]

array([4, 5])

### 矩阵格式（多维的格式）

In [41]:
z_array = np.array([[1,2,3], [4,5,6],[7,8,9]])

In [42]:
z_array.size

9

In [43]:
z_array.ndim

2

In [44]:
z_array[1,2] # ndarray取值，修改

6

In [46]:
z_array[1,2] = 100
z_array[1,2]

100

In [47]:
z_array[1] # 取第一行

array([  4,   5, 100])

In [48]:
z_array[:,1] # 取第一列

array([2, 5, 8])

In [49]:
z_array2 = z_array

In [50]:
z_array2[1,1] = 99

In [51]:
z_array2

array([[  1,   2,   3],
       [  4,  99, 100],
       [  7,   8,   9]])

In [52]:
z_array

array([[  1,   2,   3],
       [  4,  99, 100],
       [  7,   8,   9]])

In [53]:
z_array3 = z_array.copy() # 复制

In [54]:
z_array3[1,1] = 9999

In [55]:
z_array3

array([[   1,    2,    3],
       [   4, 9999,  100],
       [   7,    8,    9]])

In [56]:
z_array

array([[  1,   2,   3],
       [  4,  99, 100],
       [  7,   8,   9]])

In [58]:
z_array = np.arange(0,100,10) # 等差数组构造ndarray
z_array

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [62]:
mask = np.array([0,0,0,1,1,1,0,0,1,1], dtype=bool) # 使用dtype
mask

array([False, False, False,  True,  True,  True, False, False,  True,
        True])

In [63]:
z_array[mask] # bool类型可以当索引，为True才取值

array([30, 40, 50, 80, 90])

In [94]:
random_array = np.random.rand(10) # 产生10个0-1之间的随机数
random_array 

array([0.79138679, 0.07523853, 0.40154422, 0.42461649, 0.51818857,
       0.23749917, 0.71272077, 0.72654665, 0.54510929, 0.60022003])

In [67]:
mask = random_array > 0.5
mask

array([ True,  True,  True,  True, False, False,  True,  True, False,
       False])

In [68]:
z_array[random_array>0.5]

array([ 0, 10, 20, 30, 60, 70])

In [69]:
z_array = np.array([10,20,30,40,50])
z_array > 30

array([False, False, False,  True,  True])

In [74]:
np.where(z_array >30) # where可以得到合格元素的索引值

(array([3, 4]),)

In [75]:
z_array[np.where(z_array>30)] # where可以得到合格元素

array([40, 50])

In [77]:
z_array = np.array([1,2,3,4,5],dtype=np.float32) # 构造ndarray时指定元素类型

In [78]:
z_array.dtype

dtype('float32')

In [81]:
z_array.nbytes # 查看ndarray一共占用的字节

20

In [84]:
z_array = np.array([1,23.5,'str'], dtype=np.object) # 如果啥都想放，可以指定类型为np.object
z_array

array([1, 23.5, 'str'], dtype=object)

In [85]:
z_array * 2 # 对数值就是乘，对字符串就是翻倍

array([2, 47.0, 'strstr'], dtype=object)

In [89]:
z_array = np.array([1,2,3,4,5])
z_array2 = np.asarray(z_array, dtype = np.float32) # 基于一个array，生成一个新的array
z_array2

array([1., 2., 3., 4., 5.], dtype=float32)

In [87]:
z_array

array([1, 2, 3, 4, 5])

In [92]:
z_array.astype(np.float32) # 同样可以是用astype，也是生成新的array，并不会改变原来的array

array([1., 2., 3., 4., 5.], dtype=float32)

In [93]:
z_array

array([1, 2, 3, 4, 5])