### 随机模块

In [1]:
import numpy as np

In [4]:
# 构造3行2列的随机浮点数，0~1之间
np.random.rand(3,2)

array([[0.15045237, 0.04764185],
       [0.83833351, 0.67475054],
       [0.03911211, 0.70538176]])

In [8]:
# 构造随机整数，从0~10,不包括10
np.random.randint(10,size=(5,4))

array([[0, 7, 6, 6],
       [0, 4, 6, 8],
       [4, 8, 3, 5],
       [7, 1, 9, 4],
       [9, 4, 9, 9]])

In [11]:
# 返回1个数
np.random.randint(10)

8

In [13]:
# 随机1个0~1之间的数
np.random.random_sample()

0.15712719301687417

In [15]:
# 得到1维ndarray
np.random.randint(0,10,size=3)

array([6, 7, 5])

In [20]:
# 设置np的打印精度
np.set_printoptions(precision=3)

In [21]:
# 高斯分布，正态分布
mu, sigma = 0, 0.1
n = np.random.normal(mu, sigma, 10)
n

array([-0.037,  0.002,  0.006,  0.071, -0.122,  0.019,  0.077,  0.151,
       -0.031, -0.108])

### 洗牌

In [23]:
z_array = np.arange(10)
z_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
np.random.shuffle(z_array)
z_array

array([2, 9, 8, 6, 7, 0, 5, 3, 4, 1])

### 随机的种子

In [60]:
# 在执行下一个随机操作前指定种子，下一个随机操作结果不会变；在做对比实验的时候，可能需要
np.random.seed(0)

In [61]:
mu, sigma = 0, 0.1
n = np.random.normal(mu, sigma, 10)
n

array([ 0.176,  0.04 ,  0.098,  0.224,  0.187, -0.098,  0.095, -0.015,
       -0.01 ,  0.041])