In [1]:
import numpy as np
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(2,20,2, dtype=np.float32)

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18.], dtype=float32)

In [4]:
# 注意 linspace是有尾巴的，arange没有
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [7]:
# 默认以10为底的，对数平分成5份
np.logspace(0,2,5)

array([  1.        ,   3.16227766,  10.        ,  31.6227766 ,
       100.        ])

In [16]:

x = np.linspace(-10,10,5)
x

array([-10.,  -5.,   0.,   5.,  10.])

In [17]:
y = np.linspace(-10,10,5)
y

array([-10.,  -5.,   0.,   5.,  10.])

In [18]:
# 用x和y构造网格
x, y = np.meshgrid(x,y)

In [19]:

x

array([[-10.,  -5.,   0.,   5.,  10.],
       [-10.,  -5.,   0.,   5.,  10.],
       [-10.,  -5.,   0.,   5.,  10.],
       [-10.,  -5.,   0.,   5.,  10.],
       [-10.,  -5.,   0.,   5.,  10.]])

In [20]:
y

array([[-10., -10., -10., -10., -10.],
       [ -5.,  -5.,  -5.,  -5.,  -5.],
       [  0.,   0.,   0.,   0.,   0.],
       [  5.,   5.,   5.,   5.,   5.],
       [ 10.,  10.,  10.,  10.,  10.]])

In [21]:
# 构造行向量
np.r_[0:10:1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
# 构造列向量
np.c_[0:10:1]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

### 更常用的生成函数

In [24]:
# 用0填充
np.zeros(3, dtype=int)

array([0, 0, 0])

In [25]:
np.zeros((3,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [26]:
# 用1填充
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [27]:
# 用n填充
n = 100
np.ones((3,3)) * n

array([[100., 100., 100.],
       [100., 100., 100.],
       [100., 100., 100.]])

In [34]:
# empty
x = np.empty(5)
print(x)
x.shape

[1. 1. 1. 1. 1.]


(5,)

In [35]:
x.fill(1)
x

array([1., 1., 1., 1., 1.])

In [37]:
z_array =np.array([1,2,3,4])
z_array

array([1, 2, 3, 4])

In [40]:
# 生成全0的矩阵，形状是和谁一样的
np.zeros_like(z_array)

array([0, 0, 0, 0])

In [41]:
# 生成全1的矩阵，形状是和谁一样的
np.ones_like(z_array)

array([1, 1, 1, 1])

In [45]:
# 生成单位矩阵，只有主对角线 值为1，其他都为0
np.identity(5, dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])